#!/bin/bash

DIR="$(dirname "$0")"
PI_IMAGE_FILE="$1"
shift
NAME="${1-pi:latest}"
shift

echo "Creating docker image ${name} from disk image ${PI_IMAGE_FILE}"
echo "This will take some time."

"${DIR}/rpi-image-tool" export - | docker import - "${NAME}" "$@"
