#!/bin/bash

#### Append a file from or source data to a file in the image.
#### Result will be placed in the \${PI_PENDING} directory for later installation.
####   Usage: ${PI_INVOKER} <src> <dest>

appendLine() {
    echo "${2:?}" >>"${1:?}"
}

append() {
    local src="${PI_ROOT:?}/${1:?}"
    local data="${PI_LOCAL:?}/{$1:?}"
    local saved="${PI_SAVED:?}/${1:?}"
    local pending="${PI_PENDING:?}/${1:?}"
    if [ ! -r "${src}" ]; then
        echo "File ${src} does not exist." 1>&2
        exit 2
    fi
    mkdir -p "$(dirname "${saved}")" "$(dirname "${tmp}")" "$(dirname "${pending}")" \
    && ([ -e "${saved}" ] || cp "${src}" "${saved}" ) \
    && ([ -e "${pending}" ] || cp "${src}" "${pending}" ) \
    && appendLine "${pending}" '## Added' \
    && cat "${data}" >>"${pending}"
}

append "${1:?}"
