#!/bin/bash

#### Export the current image as a Raspbery Pi image file.
#### Usage: ${PI_INVOKER} <.img file>|<.zip file>|'-'

IMG="${1:?}"
IMGDIR="$(dirname "${PI_IMAGE_SRC_MOUNT}")"
IMGNAME="$(basename -s .zip -a "$(basename -s .img -a "${IMG}")").img"

if [ "${IMG: -4}" = '.zip' ]; then
    TMPZIP="/tmp/$$.$RANDOM.zip"
    cd "${IMGDIR}"
    if [ "${IMGNAME}" != "$(basename -a "${PI_IMAGE_FILE}")" ]; then
        ln -s "${PI_IMAGE_FILE}" "${IMGNAME}"
        zip -q "${TMPZIP}" "${IMGNAME}"
        rm "${IMGNAME}"
    else
        zip -q "${TMPZIP}" "${IMGNAME}"
    fi
    ls -ld "${IMGDIR}" "${IMGDIR}"/*
    dd status=progress conv=fsync if="${TMPZIP}" of="${PI_IMAGE_SRC_MOUNT}"
elif [ "${PI_IMAGE_ARG}" = '-' ]; then
    dd status=progress conv=fsync if="${PI_IMAGE_FILE}" bs=512
else
    dd status=progress conv=fsync if="${PI_IMAGE_FILE}" bs=512 of="${PI_IMAGE_SRC_MOUNT}"
fi
