#!/bin/bash

### Display help for other commands.

export PI_INVOKER_BASE_1="${PI_INVOKER_BASE-$0}"
SUBCMD="$1"

case "${SUBCMD}" in
    --help|'-?'|'')
        (
            echo "Usage ${PI_INVOKER} $(basename -a "$0") <cmd>"
            echo "Commands: "
            find "${PI_CMDS}" -type f -maxdepth 1 -printf '  %f\n'
        )1>&2
        exit 0
        ;;
esac

. "${PI_INCLUDES}/vars.sh"

# Discard the 'help' subcommand so we are documenting the actual command.
export PI_INVOKER_BASE="${PI_INVOKER_BASE_1}"
export PI_INVOKER="${PI_INVOKER_BASE} ${SUBCMD}"

T="$(type -t "${SUBCMD}")"
case "${T}" in
    file)
        if [ -r "${PI_CMDS}/$(basename -a "${SUBCMD}")" ]; then
            usage "${PI_CMDS}/${SUBCMD}"
            exit 0
        elif [ ! -z "$(which "${SUBCMD}")" ]; then
            msg "${SUBCMD} runs $(which "${SUBCMD}") with the image mounted."
            msg "Try ${PI_INVOKER} ${SUBCMD} --help"
            exit 0
        else
            error "Dunno what ${SUBCMD} is, but bash seems to think it is a file somewhere. 'which ${SUBCMD}' disagrees."
        fi
        ;;
    alias|keyword|function|builtin)
        msg "${SUBCMD} is a bash ${T}. It will be run with the image mounted."
        exit 0;
        ;;
    '')
        msg "${SUBCMD} does not appear to be a valid subcommand."
        exit 2
        ;;
    *)
        msg "${SUBCMD} is a ${T}, which is not a known type of command."
        exit 2
        ;;
esac
