#!/bin/bash

#### Set the hostname in /etc/hostname and /etc/hosts. Result is in ${PI_PENDING for installation on commit.
####   Usage: ${PI_INVOKER} <hostname>


hostname="${1:?}"
msg "Setting hostname to ${hostname,,}"
mkdir -p "${PI_PENDING}/etc"
echo "${hostname,,}" >"${PI_PENDING}/etc/hostname"
printf "127.0.0.1\t${hostname}" >>/etc/hosts
